package com.lvr.kdshop.business.mapper;

import com.lvr.kdshop.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    int updateLastLoginByPrimaryKey(User record);

    int updateByPrimaryKeySelective(User record);

    User getUserByPhone(@Param("phone") String phone);

    List<User> getUserList();

    int updateGoodsNum(@Param("id") String id, @Param("goodsNum") Integer goodsNum);

    int updateImgUrl(@Param("id") String id, @Param("url") String url);

    Integer checkUserByPhone(@Param("phone") String phone);

    int updatePasswordByPrimaryKey(@Param("uid") String uid, @Param("password") String password);

    List<User> searchUserByNameOrPhone(@Param("name") String name, @Param("phone") String phone);

}