package com.lvr.kdshop.business.service;

import com.lvr.kdshop.pojo.Orders;

import java.util.List;

public interface OrdersService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    List<Orders> selectAll();



    List<Orders> selectOrdersByUserId(String userId);

    Orders selectOrdersByGoodId(Integer goodId);

    Double getSpendByUserId(String userId);

    Double getIncomeByUserId(String userId);
}
