package com.lvr.kdshop.business.service;


import com.lvr.kdshop.pojo.SysUser;

import java.util.List;

public interface UserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    SysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    List<SysUser> selectAll();

    int updateByPrimaryKey(SysUser record);

    int updateLastLoginByPrimaryKey(SysUser record);

    int updateByPrimaryKeySelective(SysUser record);

    SysUser getUserByPhone(String phone);

    List<SysUser> getUserList();

    int updateGoodsNum(String id, Integer goodsNum);

    int updateImgUrl(String id, String url);

    Integer checkUserByPhone(String phone);

    int updatePasswordByPrimaryKey(String uid, String password);

    List<SysUser> searchUserByNameOrPhone(String name, String phone);
}
