package com.lvr.kdshop.business.service;


import com.lvr.kdshop.pojo.User;

import java.util.List;

public interface UserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    int updateByPrimaryKey(User record);

    int updateLastLoginByPrimaryKey(User record);

    int updateByPrimaryKeySelective(User record);

    User getUserByPhone(String phone);

    List<User> getUserList();

    int updateGoodsNum(String id, Integer goodsNum);

    int updateImgUrl(String id, String url);

    Integer checkUserByPhone(String phone);

    int updatePasswordByPrimaryKey(String uid, String password);

    List<User> searchUserByNameOrPhone(String name, String phone);
}
