server:
  port: 8888

# springboot数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.102.163:3306/kdshop?serverTimezone=GMT%2B8&useSSL=FALSE
    username: kdshop  #数据库用户名
    password: kdshop #该数据库用户的密码
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 20MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8

mybatis:  #mybatyis的配置
  mapper-locations: classpath*:mapper/*.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  type-aliases-package: com.lvr.kdshop.pojo
  config-location: classpath:mybatis/mybatis-config.xml

# 日志
logging:
  config: classpath:logback.xml

# 上传文件模式：local为本地上传，需要配置下方的imagesPath；
#             oss为阿里云上传，需要在阿里云中开通对象存储服务，配置相应的key
uploadMode: local
# 文件上传映射本地路径
# 在项目的源文件夹中建立upload目录，用于文件上传
imagesPath: C:/Users/My VM/Desktop/kd-shop/kd-shop/upload/
# 图片映射地址
fileUploadPathRelative: /images/**